[workspace]
authors = ["kozo <kozoYang@outlook.com>"]
channels = ["conda-forge"]
name = "cute-kernels"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cuda = "12.6.*"
cxx-compiler = "*"
c-compiler = "*"
make = ">=4.4.1,<5"
cmake = ">=4.0.0,<5"
pip = ">=25.0.1,<26"
python = "3.10.*"
sysroot_linux-64 = "2.34"
