context:
  name: "cute-kernel"
  version: 0.1.0
  build_number: 0

package:
  name: ${{ name }}
  version: ${{ version }}
source:
  - path: ./cute-gemm
build:
  number: ${{ build_number }}
  script:
    - |
      export MAX_JOBS=$(($CPU_COUNT / 2 > 32 ? 32 : $CPU_COUNT / 2 ))
      export CUDA_HOME=$BUILD_PREFIX
    - cmake -S . -B build $CMAKE_ARGS -DCMAKE_EXPORT_COMPILE_COMMANDS=1
    - cp build/compile_commands.json $RECIPE_DIR/
    - cmake --build build -j $MAX_JOBS
    - cmake --install build --prefix $PREFIX
    - cp build/gemm/gemm* $PREFIX/bin/

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('cuda') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
    - git
  host:
    - cuda-cudart-dev =${{ cuda_compiler_version }}
    - cuda-libraries-dev
    - cuda-tools
  run:
    - cuda-libraries

tests: 
  - script: 
    - gemm_self
    - gemm_blas
